<?php

include('connection.php');

if (isset($_POST['submit'])) {

    $numbers = rand(9000, 110000);
    shuffle($numbers);
    $memberId = $numbers;

    $tdate = date("l-m-Y");

    $course_name = $_POST['course_name'];

    $customer_name = $_POST['customer_name'];
    $customer_email = $_POST['customer_email'];
    $customer_phone = $_POST['customer_phone'];
    /* $customer_age = $_POST['customer_age'];
    $customer_address = $_POST['customer_address']; */

    $c_subject = "Registration Form Submitted By " . $customer_name;

    $query = "INSERT INTO tblregistration (id, course_name, customer_name, customer_email, customer_phone) 
    VALUES ('$memberId', '$course_name', '$customer_name', '$customer_email', '$customer_phone')";

    $to = "sonambenawat@gmail.com";

    $txt = " Hi! Rythmic Vibes, " . "\r\n Your " . $course_name . " is registered by " . $customer_name . " on " . $tdate . "\r\n" . " \r\n Unique Member Id generated by system = " . $memberId . " \r\n Candidate Name = " . $customer_name . "\r\n Mobile Number = " . $customer_phone . "\r\n Email Address = " . $customer_email;

    $headers = "From: " . $customer_email;

    mail($to, $c_subject, $txt, $headers);

    if (mysqli_query($con, $query)) {
        /* $msg = "Registration Successfull. Copy this member ID for future use ".$memberId . " <a href = 'payment.php' style = 'border:solid 1px #A23C86; background-color:#A23C86; color:white; padding:4px;'>Proceed to payment</a>"; */
        echo '<div id="popup">
                Record added successfully. <button onclick="myFunction()" style="font-size:26px;"> &times; </button> <br/><br/>
                <a target = "_blank" href = "https://us02web.zoom.us/j/81784015375?pwd=NmJTTDgrNTZta0Uza2pnVHM1QnIvQT09"><span style = "font-size:28px;"><u>Join Zoom Meeting</u></span></a>
                <br><br>
                Meeting ID: 817 8401 5375<br/>
                Passcode: 199555
                </div>';
    } else {
        $msg = "Something Went Wrong. Please try again.";
    }
}

?>
<!DOCTYPE html>
<html lang="zxx">

<head>

    <title>Free Webinar Registration - Rythmic Vibe</title>

    <style>
        #popup {
            visibility: hidden;
            background-color: #a23c86;
            color: white;
            position: fixed;
            /* top: 20px; */
            z-index: 100;
            height: 240px;
            width: 280px;
            bottom: 10px;
            left: 10px;
            padding: 30px 20px 30px 20px;
            /* top: 20px; */
        }
    </style>

    <!-- header -->
    <?php include('inner-header.php'); ?>
    <!--Header End-->
    </div>
    <!--Full width header End-->

    <!-- Main content Start -->
    <div class="main-content">

        <!-- Breadcrumbs Start -->
        <div class="rs-breadcrumbs breadcrumbs-overlay ">
            <div class="breadcrumbs-img">
                <img src="assets/images/bg/registration.jpg" alt="Registration">
            </div>
        </div>
        <!-- Breadcrumbs End -->

        <!-- Contact Section Start -->
        <div class="contact-page-section pt-5 pb-100 md-pt-70 md-pb-70">
            <div class="container">

                <div class="rs-quick-contact">
                    <div class="inner-part text-center mb-50">
                        <h2 class="title mb-15">Free Webinar Registration</h2>
                    </div>

                    <div id="form-messages" style="color:red; margin-bottom:15px;"> <?php echo @$msg; ?> </div>

                    <form method="post" enctype="multipart/form-data">
                        <div class="row">

                            <div class="col-lg-6 mb-35 col-md-12">
                                <select name="course_name" id="course_name" class="form-control" required>
                                    <option disabled selected>Select Course</option>
                                    <option value="Power of money vibrations">Power of money vibrations</option>
                                    <!-- <option value="Self Love Course">Self Love Course</option>
                                    <option value="Speaking English Course">Speaking English Course</option>
                                    <option value="Life changing habits to live a perfect and happy life">Life changing habits to live a perfect and happy life</option> -->
                                </select>
                            </div>

                            <div class="col-lg-6 mb-35 col-md-12">
                                <input type="text" name="customer_name" id="customer_name" class="form-control" placeholder="Enter Full Name" required>
                            </div>

                            <div class="col-lg-6 mb-35 col-md-12">
                                <input type="email" name="customer_email" id="customer_email" class="form-control" placeholder="Email Address" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" required>
                            </div>

                            <div class="col-lg-6 mb-35 col-md-12">
                                <input type="tel" name="customer_phone" id="customer_phone" required pattern="[0-9]{3}[0-9]{3}[0-9]{4}" class="form-control" placeholder="Phone">
                            </div>

                            <!-- <div class="col-lg-12 mb-35 col-md-12">
                                <input type="text" name="customer_age" id="customer_age" required class="form-control" placeholder="Age">
                            </div> -->

                            <!-- <div class="col-lg-6 mb-35 col-md-12">
                                <input type="text" name="customer_city" id="customer_city" required class="form-control" placeholder="City">
                            </div>

                            <div class="col-lg-6 mb-35 col-md-12">
                                <select name="customer_state" id="customer_state" required class="form-control">
                                    <option disabled selected>Select State</option>
                                    <option value="Andhra Pradesh">Andhra Pradesh</option>
                                    <option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
                                    <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                                    <option value="Assam">Assam</option>
                                    <option value="Bihar">Bihar</option>
                                    <option value="Chandigarh">Chandigarh</option>
                                    <option value="Chhattisgarh">Chhattisgarh</option>
                                    <option value="Dadar and Nagar Haveli">Dadar and Nagar Haveli</option>
                                    <option value="Daman and Diu">Daman and Diu</option>
                                    <option value="Delhi">Delhi</option>
                                    <option value="Lakshadweep">Lakshadweep</option>
                                    <option value="Puducherry">Puducherry</option>
                                    <option value="Goa">Goa</option>
                                    <option value="Gujarat">Gujarat</option>
                                    <option value="Haryana">Haryana</option>
                                    <option value="Himachal Pradesh">Himachal Pradesh</option>
                                    <option value="Jammu and Kashmir">Jammu and Kashmir</option>
                                    <option value="Jharkhand">Jharkhand</option>
                                    <option value="Karnataka">Karnataka</option>
                                    <option value="Kerala">Kerala</option>
                                    <option value="Madhya Pradesh">Madhya Pradesh</option>
                                    <option value="Maharashtra">Maharashtra</option>
                                    <option value="Manipur">Manipur</option>
                                    <option value="Meghalaya">Meghalaya</option>
                                    <option value="Mizoram">Mizoram</option>
                                    <option value="Nagaland">Nagaland</option>
                                    <option value="Odisha">Odisha</option>
                                    <option value="Punjab">Punjab</option>
                                    <option value="Rajasthan">Rajasthan</option>
                                    <option value="Sikkim">Sikkim</option>
                                    <option value="Tamil Nadu">Tamil Nadu</option>
                                    <option value="Telangana">Telangana</option>
                                    <option value="Tripura">Tripura</option>
                                    <option value="Uttar Pradesh">Uttar Pradesh</option>
                                    <option value="Uttarakhand">Uttarakhand</option>
                                    <option value="West Bengal">West Bengal</option>
                                </select>
                            </div>

                            <div class="col-lg-6 mb-35 col-md-12">

                                <select id="customer_country" name="customer_country" class="form-control" required>
                                    <option disabled selected> Select Country </option>
                                    <option value="Argentina">Argentina</option>
                                    <option value="Australia">Australia</option>
                                    <option value="Austria">Austria</option>
                                    <option value="Bangladesh">Bangladesh</option>
                                    <option value="Belgium">Belgium</option>
                                    <option value="Bhutan">Bhutan</option>
                                    <option value="Bolivia">Bolivia</option>
                                    <option value="Brazil">Brazil</option>
                                    <option value="Bulgaria">Bulgaria</option>
                                    <option value="Burundi">Burundi</option>
                                    <option value="Cambodia">Cambodia</option>
                                    <option value="Canada">Canada</option>
                                    <option value="China">China</option>
                                    <option value="Colombia">Colombia</option>
                                    <option value="Congo">Congo</option>
                                    <option value="Congo, The Democratic Republic of The">Congo, The Democratic Republic of The</option>
                                    <option value="Cook Islands">Cook Islands</option>
                                    <option value="Costa Rica">Costa Rica</option>
                                    <option value="Cote D'ivoire">Cote D'ivoire</option>
                                    <option value="Croatia">Croatia</option>
                                    <option value="Cuba">Cuba</option>
                                    <option value="Cyprus">Cyprus</option>
                                    <option value="Czech Republic">Czech Republic</option>
                                    <option value="Denmark">Denmark</option>
                                    <option value="Djibouti">Djibouti</option>
                                    <option value="Dominica">Dominica</option>
                                    <option value="Dominican Republic">Dominican Republic</option>
                                    <option value="Ecuador">Ecuador</option>
                                    <option value="Egypt">Egypt</option>
                                    <option value="El Salvador">El Salvador</option>
                                    <option value="Equatorial Guinea">Equatorial Guinea</option>
                                    <option value="Eritrea">Eritrea</option>
                                    <option value="Estonia">Estonia</option>
                                    <option value="Ethiopia">Ethiopia</option>
                                    <option value="Falkland Islands (Malvinas)">Falkland Islands (Malvinas)</option>
                                    <option value="Faroe Islands">Faroe Islands</option>
                                    <option value="Fiji">Fiji</option>
                                    <option value="Finland">Finland</option>
                                    <option value="France">France</option>
                                    <option value="French Guiana">French Guiana</option>
                                    <option value="French Polynesia">French Polynesia</option>
                                    <option value="French Southern Territories">French Southern Territories</option>
                                    <option value="Gabon">Gabon</option>
                                    <option value="Gambia">Gambia</option>
                                    <option value="Georgia">Georgia</option>
                                    <option value="Germany">Germany</option>
                                    <option value="Ghana">Ghana</option>
                                    <option value="Gibraltar">Gibraltar</option>
                                    <option value="Greece">Greece</option>
                                    <option value="Greenland">Greenland</option>
                                    <option value="Grenada">Grenada</option>
                                    <option value="Guadeloupe">Guadeloupe</option>
                                    <option value="Guam">Guam</option>
                                    <option value="Guatemala">Guatemala</option>
                                    <option value="Guernsey">Guernsey</option>
                                    <option value="Guinea">Guinea</option>
                                    <option value="Guinea-bissau">Guinea-bissau</option>
                                    <option value="Guyana">Guyana</option>
                                    <option value="Haiti">Haiti</option>
                                    <option value="Heard Island and Mcdonald Islands">Heard Island and Mcdonald Islands</option>
                                    <option value="Holy See (Vatican City State)">Holy See (Vatican City State)</option>
                                    <option value="Honduras">Honduras</option>
                                    <option value="Hong Kong">Hong Kong</option>
                                    <option value="Hungary">Hungary</option>
                                    <option value="Iceland">Iceland</option>
                                    <option value="India">India</option>
                                    <option value="Indonesia">Indonesia</option>
                                    <option value="Iran, Islamic Republic of">Iran, Islamic Republic of</option>
                                    <option value="Iraq">Iraq</option>
                                    <option value="Ireland">Ireland</option>
                                    <option value="Isle of Man">Isle of Man</option>
                                    <option value="Israel">Israel</option>
                                    <option value="Italy">Italy</option>
                                    <option value="Jamaica">Jamaica</option>
                                    <option value="Japan">Japan</option>
                                    <option value="Jersey">Jersey</option>
                                    <option value="Jordan">Jordan</option>
                                    <option value="Kazakhstan">Kazakhstan</option>
                                    <option value="Kenya">Kenya</option>
                                    <option value="Kiribati">Kiribati</option>
                                    <option value="Korea, Democratic People's Republic of">Korea, Democratic People's Republic of</option>
                                    <option value="Korea, Republic of">Korea, Republic of</option>
                                    <option value="Kuwait">Kuwait</option>
                                    <option value="Kyrgyzstan">Kyrgyzstan</option>
                                    <option value="Lao People's Democratic Republic">Lao People's Democratic Republic</option>
                                    <option value="Latvia">Latvia</option>
                                    <option value="Lebanon">Lebanon</option>
                                    <option value="Lesotho">Lesotho</option>
                                    <option value="Liberia">Liberia</option>
                                    <option value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</option>
                                    <option value="Liechtenstein">Liechtenstein</option>
                                    <option value="Lithuania">Lithuania</option>
                                    <option value="Luxembourg">Luxembourg</option>
                                    <option value="Macao">Macao</option>
                                    <option value="Macedonia, The Former Yugoslav Republic of">Macedonia, The Former Yugoslav Republic of</option>
                                    <option value="Madagascar">Madagascar</option>
                                    <option value="Malawi">Malawi</option>
                                    <option value="Malaysia">Malaysia</option>
                                    <option value="Maldives">Maldives</option>
                                    <option value="Mali">Mali</option>
                                    <option value="Malta">Malta</option>
                                    <option value="Marshall Islands">Marshall Islands</option>
                                    <option value="Martinique">Martinique</option>
                                    <option value="Mauritania">Mauritania</option>
                                    <option value="Mauritius">Mauritius</option>
                                    <option value="Mayotte">Mayotte</option>
                                    <option value="Mexico">Mexico</option>
                                    <option value="Micronesia, Federated States of">Micronesia, Federated States of</option>
                                    <option value="Moldova, Republic of">Moldova, Republic of</option>
                                    <option value="Monaco">Monaco</option>
                                    <option value="Mongolia">Mongolia</option>
                                    <option value="Montenegro">Montenegro</option>
                                    <option value="Montserrat">Montserrat</option>
                                    <option value="Morocco">Morocco</option>
                                    <option value="Mozambique">Mozambique</option>
                                    <option value="Myanmar">Myanmar</option>
                                    <option value="Namibia">Namibia</option>
                                    <option value="Nauru">Nauru</option>
                                    <option value="Nepal">Nepal</option>
                                    <option value="Netherlands">Netherlands</option>
                                    <option value="Netherlands Antilles">Netherlands Antilles</option>
                                    <option value="New Caledonia">New Caledonia</option>
                                    <option value="New Zealand">New Zealand</option>
                                    <option value="Nicaragua">Nicaragua</option>
                                    <option value="Niger">Niger</option>
                                    <option value="Nigeria">Nigeria</option>
                                    <option value="Niue">Niue</option>
                                    <option value="Norfolk Island">Norfolk Island</option>
                                    <option value="Northern Mariana Islands">Northern Mariana Islands</option>
                                    <option value="Norway">Norway</option>
                                    <option value="Oman">Oman</option>
                                    <option value="Pakistan">Pakistan</option>
                                    <option value="Palau">Palau</option>
                                    <option value="Palestinian Territory, Occupied">Palestinian Territory, Occupied</option>
                                    <option value="Panama">Panama</option>
                                    <option value="Papua New Guinea">Papua New Guinea</option>
                                    <option value="Paraguay">Paraguay</option>
                                    <option value="Peru">Peru</option>
                                    <option value="Philippines">Philippines</option>
                                    <option value="Pitcairn">Pitcairn</option>
                                    <option value="Poland">Poland</option>
                                    <option value="Portugal">Portugal</option>
                                    <option value="Puerto Rico">Puerto Rico</option>
                                    <option value="Qatar">Qatar</option>
                                    <option value="Reunion">Reunion</option>
                                    <option value="Romania">Romania</option>
                                    <option value="Russian Federation">Russian Federation</option>
                                    <option value="Rwanda">Rwanda</option>
                                    <option value="Saint Helena">Saint Helena</option>
                                    <option value="Saint Kitts and Nevis">Saint Kitts and Nevis</option>
                                    <option value="Saint Lucia">Saint Lucia</option>
                                    <option value="Saint Pierre and Miquelon">Saint Pierre and Miquelon</option>
                                    <option value="Saint Vincent and The Grenadines">Saint Vincent and The Grenadines</option>
                                    <option value="Samoa">Samoa</option>
                                    <option value="San Marino">San Marino</option>
                                    <option value="Sao Tome and Principe">Sao Tome and Principe</option>
                                    <option value="Saudi Arabia">Saudi Arabia</option>
                                    <option value="Senegal">Senegal</option>
                                    <option value="Serbia">Serbia</option>
                                    <option value="Seychelles">Seychelles</option>
                                    <option value="Sierra Leone">Sierra Leone</option>
                                    <option value="Singapore">Singapore</option>
                                    <option value="Slovakia">Slovakia</option>
                                    <option value="Slovenia">Slovenia</option>
                                    <option value="Solomon Islands">Solomon Islands</option>
                                    <option value="Somalia">Somalia</option>
                                    <option value="South Africa">South Africa</option>
                                    <option value="South Georgia and The South Sandwich Islands">South Georgia and The South Sandwich Islands</option>
                                    <option value="Spain">Spain</option>
                                    <option value="Sri Lanka">Sri Lanka</option>
                                    <option value="Sudan">Sudan</option>
                                    <option value="Suriname">Suriname</option>
                                    <option value="Svalbard and Jan Mayen">Svalbard and Jan Mayen</option>
                                    <option value="Swaziland">Swaziland</option>
                                    <option value="Sweden">Sweden</option>
                                    <option value="Switzerland">Switzerland</option>
                                    <option value="Syrian Arab Republic">Syrian Arab Republic</option>
                                    <option value="Taiwan">Taiwan</option>
                                    <option value="Tajikistan">Tajikistan</option>
                                    <option value="Tanzania, United Republic of">Tanzania, United Republic of</option>
                                    <option value="Thailand">Thailand</option>
                                    <option value="Timor-leste">Timor-leste</option>
                                    <option value="Togo">Togo</option>
                                    <option value="Tokelau">Tokelau</option>
                                    <option value="Tonga">Tonga</option>
                                    <option value="Trinidad and Tobago">Trinidad and Tobago</option>
                                    <option value="Tunisia">Tunisia</option>
                                    <option value="Turkey">Turkey</option>
                                    <option value="Turkmenistan">Turkmenistan</option>
                                    <option value="Turks and Caicos Islands">Turks and Caicos Islands</option>
                                    <option value="Tuvalu">Tuvalu</option>
                                    <option value="Uganda">Uganda</option>
                                    <option value="Ukraine">Ukraine</option>
                                    <option value="United Arab Emirates">United Arab Emirates</option>
                                    <option value="United Kingdom">United Kingdom</option>
                                    <option value="United States">United States</option>
                                    <option value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
                                    <option value="Uruguay">Uruguay</option>
                                    <option value="Uzbekistan">Uzbekistan</option>
                                    <option value="Vanuatu">Vanuatu</option>
                                    <option value="Venezuela">Venezuela</option>
                                    <option value="Viet Nam">Viet Nam</option>
                                    <option value="Virgin Islands, British">Virgin Islands, British</option>
                                    <option value="Virgin Islands, U.S.">Virgin Islands, U.S.</option>
                                    <option value="Wallis and Futuna">Wallis and Futuna</option>
                                    <option value="Western Sahara">Western Sahara</option>
                                    <option value="Yemen">Yemen</option>
                                    <option value="Zambia">Zambia</option>
                                    <option value="Zimbabwe">Zimbabwe</option>
                                </select>
                            </div> -->

                            <!-- <div class="col-lg-12 mb-35 col-md-12">
                                <textarea name="customer_address" id="customer_address" required class="form-control" placeholder="Address"></textarea>
                            </div> -->

                        </div>
                        <div class="form-group mb-0">
                            <button type="submit" name="submit" class="btn-send">
                                Submit
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- Contact Section End -->

        <?php include('float_buttons.php'); ?>

        <?php
        echo '
       <script type="text/javascript">
         function hideMsg()
         {
            document.getElementById("popup").style.visibility = "hidden";
         }

         document.getElementById("popup").style.visibility = "visible";
       </script>';
        ?>
        <!-- window.setTimeout("hideMsg()", 2000); -->

    </div>
    <!-- Main content End -->

    <!-- Footer Start -->
    <?php include('footer.php'); ?>
    <!-- Footer End -->
    

    <!-- modernizr js -->
    <script src="assets/js/modernizr-2.8.3.min.js"></script>

    <!-- jquery latest version -->
    <script src="assets/js/jquery.min.js"></script>

    <!-- Bootstrap v4.4.1 js -->
    <script src="assets/js/bootstrap.min.js"></script>

    <!-- Menu js -->
    <script src="assets/js/rsmenu-main.js"></script>

    <!-- op nav js -->
    <script src="assets/js/jquery.nav.js"></script>

    <!-- owl.carousel js -->
    <script src="assets/js/owl.carousel.min.js"></script>

    <!-- Slick js -->
    <script src="assets/js/slick.min.js"></script>

    <!-- isotope.pkgd.min js -->
    <script src="assets/js/isotope.pkgd.min.js"></script>

    <!-- imagesloaded.pkgd.min js -->
    <script src="assets/js/imagesloaded.pkgd.min.js"></script>

    <!-- wow js -->
    <script src="assets/js/wow.min.js"></script>

    <!-- Skill bar js -->
    <script src="assets/js/skill.bars.jquery.js"></script>

    <script src="assets/js/jquery.counterup.min.js"></script>

    <!-- counter top js -->
    <script src="assets/js/waypoints.min.js"></script>

    <!-- video js -->
    <script src="assets/js/jquery.mb.YTPlayer.min.js"></script>

    <!-- magnific popup js -->
    <script src="assets/js/jquery.magnific-popup.min.js"></script>

    <!-- tilt js -->
    <script src="assets/js/tilt.jquery.min.js"></script>

    <!-- plugins js -->
    <script src="assets/js/plugins.js"></script>

    <!-- contact form js -->
    <script src="assets/js/contact.form.js"></script>

    <!-- main js -->
    <script src="assets/js/main.js"></script>
    
    <script>
        function myFunction() {
            document.getElementById("popup").style.visibility = "hidden";
        }
    </script>


    </body>

</html>